project_id = "sckglgjydlbztxjupbsk"

[functions.ai-edit-card]
verify_jwt = false

[functions.ai-reorganize-cards]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.transcribe-audio-ai]
verify_jwt = false