// Prebuilt macro library shipped with the toolbox.
// Each entry is a ready-to-install macro. Steps use the same shape as user macros
// and support {{vault.*}} tokens for credentials.
window.PREBUILT_MACROS = [
  {
    slug: 'gmail-compose',
    name: 'Compose new Gmail',
    description: 'Open Gmail and start a fresh compose window.',
    category: 'Email',
    icon: '✉️',
    start_url: 'https://mail.google.com/mail/u/0/#inbox?compose=new',
    target_domain: 'mail.google.com',
    tags: ['gmail', 'email'],
    steps: [
      { action: 'navigate', url: 'https://mail.google.com/mail/u/0/#inbox?compose=new' },
      { action: 'wait_for', selector: 'div[role="dialog"][aria-label*="essage" i]' },
      { action: 'pause', prompt: 'Compose window is open — fill it out and send when ready.' },
    ],
  },
  {
    slug: 'gmail-inbox-zero',
    name: 'Gmail — Inbox Zero pass',
    description: 'Opens Gmail, then pauses on each unread thread for you to archive / reply.',
    category: 'Email',
    icon: '📥',
    start_url: 'https://mail.google.com/mail/u/0/#inbox',
    target_domain: 'mail.google.com',
    tags: ['gmail', 'inbox'],
    steps: [
      { action: 'navigate', url: 'https://mail.google.com/mail/u/0/#inbox' },
      { action: 'wait_for', selector: 'div[role="main"]' },
      { action: 'pause', prompt: 'Triage your inbox — archive, reply, or snooze. Click Continue when finished.' },
    ],
  },
  {
    slug: 'calendar-new-event',
    name: 'New Google Calendar event',
    description: 'Jumps straight to the Google Calendar event creator.',
    category: 'Productivity',
    icon: '📅',
    start_url: 'https://calendar.google.com/calendar/u/0/r/eventedit',
    target_domain: 'calendar.google.com',
    tags: ['calendar', 'event'],
    steps: [
      { action: 'navigate', url: 'https://calendar.google.com/calendar/u/0/r/eventedit' },
      { action: 'wait_for', selector: 'input[aria-label*="title" i], input[placeholder*="title" i]' },
      { action: 'pause', prompt: 'Fill in your event details, then save.' },
    ],
  },
  {
    slug: 'drive-new-doc',
    name: 'New Google Doc',
    description: 'Creates a blank Google Doc in your Drive.',
    category: 'Productivity',
    icon: '📝',
    start_url: 'https://docs.google.com/document/u/0/create',
    target_domain: 'docs.google.com',
    tags: ['docs', 'google'],
    steps: [
      { action: 'navigate', url: 'https://docs.google.com/document/u/0/create' },
      { action: 'wait_for', selector: 'div.kix-appview-editor, body' },
      { action: 'pause', prompt: 'Your new doc is ready.' },
    ],
  },
  {
    slug: 'sheets-new',
    name: 'New Google Sheet',
    description: 'Creates a blank Google Sheet.',
    category: 'Productivity',
    icon: '📊',
    start_url: 'https://docs.google.com/spreadsheets/u/0/create',
    target_domain: 'docs.google.com',
    tags: ['sheets', 'google'],
    steps: [
      { action: 'navigate', url: 'https://docs.google.com/spreadsheets/u/0/create' },
      { action: 'wait_for', selector: 'body' },
      { action: 'pause', prompt: 'Your new sheet is ready.' },
    ],
  },
  {
    slug: 'google-search',
    name: 'Google search a topic',
    description: 'Asks you for a topic, then runs a Google search.',
    category: 'Research',
    icon: '🔎',
    start_url: 'https://www.google.com',
    target_domain: 'www.google.com',
    tags: ['search', 'research'],
    steps: [
      { action: 'ask', prompt: 'What should I search for?', var: 'topic' },
      { action: 'navigate', url: 'https://www.google.com/search?q={{var.topic}}' },
      { action: 'wait_for', selector: '#search' },
    ],
  },
  {
    slug: 'youtube-search',
    name: 'YouTube search',
    description: 'Search YouTube for whatever you type.',
    category: 'Research',
    icon: '📺',
    start_url: 'https://www.youtube.com',
    target_domain: 'www.youtube.com',
    tags: ['youtube', 'video'],
    steps: [
      { action: 'ask', prompt: 'Search YouTube for…', var: 'q' },
      { action: 'navigate', url: 'https://www.youtube.com/results?search_query={{var.q}}' },
      { action: 'wait_for', selector: 'ytd-search' },
    ],
  },
  {
    slug: 'summarize-current',
    name: 'Summarize current page to a card',
    description: 'Sends the current page to ALICE and saves the summary as a Zettel card.',
    category: 'Research',
    icon: '🧠',
    start_url: '',
    target_domain: null,
    tags: ['alice', 'summary'],
    steps: [
      { action: 'summarize_page' },
    ],
  },
  {
    slug: 'github-new-repo',
    name: 'GitHub — new repository',
    description: 'Opens the New Repository page and pauses for you to configure it.',
    category: 'Developer',
    icon: '🐙',
    start_url: 'https://github.com/new',
    target_domain: 'github.com',
    tags: ['github', 'developer'],
    steps: [
      { action: 'navigate', url: 'https://github.com/new' },
      { action: 'wait_for', selector: 'input[name="repository[name]"], input#repository_name' },
      { action: 'pause', prompt: 'Fill in repo name, visibility, and options, then create.' },
    ],
  },
  {
    slug: 'linkedin-post',
    name: 'LinkedIn — start a post',
    description: 'Opens the LinkedIn composer.',
    category: 'Social',
    icon: '💼',
    start_url: 'https://www.linkedin.com/feed/',
    target_domain: 'www.linkedin.com',
    tags: ['linkedin', 'social'],
    steps: [
      { action: 'navigate', url: 'https://www.linkedin.com/feed/' },
      { action: 'wait_for', selector: 'button[aria-label*="Start a post" i]' },
      { action: 'click', selector: 'button[aria-label*="Start a post" i]' },
      { action: 'pause', prompt: 'Write your post and click Post when ready.' },
    ],
  },
  {
    slug: 'amazon-orders',
    name: 'Amazon — review recent orders',
    description: 'Jumps to your Amazon orders page.',
    category: 'Shopping',
    icon: '📦',
    start_url: 'https://www.amazon.com/gp/your-account/order-history',
    target_domain: 'www.amazon.com',
    tags: ['amazon', 'shopping'],
    steps: [
      { action: 'navigate', url: 'https://www.amazon.com/gp/your-account/order-history' },
      { action: 'wait_for', selector: 'body' },
      { action: 'pause', prompt: 'Review your recent orders.' },
    ],
  },
  {
    slug: 'login-vault-generic',
    name: 'Log in using vault credentials',
    description: 'Auto-fills username/password on the active site from your secure vault. Edit selectors per site.',
    category: 'Auth',
    icon: '🔐',
    start_url: '',
    target_domain: null,
    tags: ['login', 'vault'],
    steps: [
      { action: 'login_vault',
        user_selector: 'input[type="email"], input[name*="user" i], input[name*="email" i]',
        pass_selector: 'input[type="password"]',
        value: { username: '{{vault.username}}', password: '{{vault.password}}' } },
      { action: 'pause', prompt: 'Solve any CAPTCHA / 2FA, then continue.' },
    ],
  },
  {
    slug: 'translate-clipboard',
    name: 'Google Translate a phrase',
    description: 'Asks for a phrase, then opens Google Translate with it.',
    category: 'Research',
    icon: '🌐',
    start_url: 'https://translate.google.com',
    target_domain: 'translate.google.com',
    tags: ['translate', 'language'],
    steps: [
      { action: 'ask', prompt: 'Phrase to translate', var: 'text' },
      { action: 'ask', prompt: 'Target language code (e.g. es, fr, de, ja)', var: 'lang' },
      { action: 'navigate', url: 'https://translate.google.com/?sl=auto&tl={{var.lang}}&text={{var.text}}&op=translate' },
      { action: 'wait_for', selector: 'span[lang]' },
    ],
  },
  {
    slug: 'morning-brief',
    name: 'Morning brief',
    description: 'Opens Gmail inbox, Google Calendar today view, and a fresh ALICE chat side-by-side.',
    category: 'Routines',
    icon: '☀️',
    start_url: 'https://mail.google.com/mail/u/0/#inbox',
    target_domain: null,
    tags: ['routine', 'morning'],
    steps: [
      { action: 'navigate', url: 'https://mail.google.com/mail/u/0/#inbox' },
      { action: 'wait', ms: 1000 },
      { action: 'alice_chat', prompt: 'Give me my morning brief: top 3 emails, today\'s calendar, and any overdue tasks.' },
    ],
  },
];
