import { useParams, useNavigate } from "react-router-dom";
import { useScholarLesson, useMarkFormatComplete } from "@/hooks/useScholar";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ArrowLeft, BookOpen, Video, Sparkles, Footprints, CheckCircle2 } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { useEffect } from "react";

export default function ScholarLesson() {
  const { slug } = useParams<{ slug: string }>();
  const navigate = useNavigate();
  const { data: lesson, isLoading } = useScholarLesson(slug);
  const markComplete = useMarkFormatComplete();

  useEffect(() => {
    document.title = lesson ? `${lesson.title} · Scholar · PendragonX` : "Scholar · PendragonX";
  }, [lesson]);

  if (isLoading) return <div className="container py-8">Loading…</div>;
  if (!lesson) {
    return (
      <div className="container py-8 space-y-4">
        <Button variant="ghost" onClick={() => navigate("/scholar")}><ArrowLeft className="mr-2 h-4 w-4" />Back to Scholar</Button>
        <Card className="p-6">
          <h2 className="text-xl font-semibold mb-2">Lesson not yet generated</h2>
          <p className="text-sm text-muted-foreground">
            The curriculum sync engine will publish this lesson on its next run. An admin can also force a resync from Admin → Scholar.
          </p>
        </Card>
      </div>
    );
  }

  const handleComplete = (format: string) => markComplete.mutate({ lessonSlug: lesson.slug, format });

  const videoEmbed = lesson.video_url ? toEmbed(lesson.video_url) : null;
  const walkthroughSteps: Array<{ target?: string; content: string }> = Array.isArray(lesson.walkthrough_json) ? lesson.walkthrough_json : [];

  return (
    <div className="container max-w-4xl py-8 space-y-6">
      <Button variant="ghost" size="sm" onClick={() => navigate("/scholar")}>
        <ArrowLeft className="mr-2 h-4 w-4" /> Back to Scholar
      </Button>

      <header className="space-y-2">
        <h1 className="text-3xl font-semibold tracking-tight">{lesson.title}</h1>
        {lesson.summary && <p className="text-muted-foreground">{lesson.summary}</p>}
      </header>

      <Tabs defaultValue="read" className="space-y-4">
        <TabsList>
          <TabsTrigger value="read"><BookOpen className="mr-2 h-4 w-4" />Read</TabsTrigger>
          <TabsTrigger value="watch" disabled={!videoEmbed}><Video className="mr-2 h-4 w-4" />Watch</TabsTrigger>
          <TabsTrigger value="walk" disabled={walkthroughSteps.length === 0}><Footprints className="mr-2 h-4 w-4" />Walkthrough</TabsTrigger>
          <TabsTrigger value="alice"><Sparkles className="mr-2 h-4 w-4" />Ask ALICE</TabsTrigger>
        </TabsList>

        <TabsContent value="read">
          <Card className="p-6 space-y-4">
            <article className="prose prose-sm dark:prose-invert max-w-none">
              <ReactMarkdown>{lesson.written_md || "_Written lesson is being generated by the curriculum sync engine._"}</ReactMarkdown>
            </article>
            <Button onClick={() => handleComplete("read")} variant="secondary" size="sm">
              <CheckCircle2 className="mr-2 h-4 w-4" /> Mark read as complete
            </Button>
          </Card>
        </TabsContent>

        <TabsContent value="watch">
          {videoEmbed && (
            <Card className="p-2 overflow-hidden">
              <div className="aspect-video w-full">
                <iframe
                  src={videoEmbed}
                  className="w-full h-full rounded"
                  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                  allowFullScreen
                  title={lesson.title}
                />
              </div>
              <div className="p-3">
                <Button onClick={() => handleComplete("watch")} variant="secondary" size="sm">
                  <CheckCircle2 className="mr-2 h-4 w-4" /> Mark watched
                </Button>
              </div>
            </Card>
          )}
        </TabsContent>

        <TabsContent value="walk">
          <Card className="p-6 space-y-3">
            <h3 className="font-semibold">Guided steps</h3>
            <ol className="space-y-2 list-decimal list-inside text-sm">
              {walkthroughSteps.map((s, i) => (
                <li key={i}>{s.content}</li>
              ))}
            </ol>
            <Button onClick={() => navigate("/scholar/sandbox")} size="sm">Open sandbox to try</Button>
            <Button onClick={() => handleComplete("walk")} variant="secondary" size="sm" className="ml-2">
              <CheckCircle2 className="mr-2 h-4 w-4" /> Mark complete
            </Button>
          </Card>
        </TabsContent>

        <TabsContent value="alice">
          <Card className="p-6 space-y-3">
            <h3 className="font-semibold">Ask ALICE about {lesson.title}</h3>
            <p className="text-sm text-muted-foreground">
              Start a focused chat with ALICE. She'll explain this feature, answer questions, and can demo it for you in the sandbox.
            </p>
            <Button onClick={() => navigate(`/alice?scholar=${lesson.slug}`)}>
              <Sparkles className="mr-2 h-4 w-4" /> Open ALICE
            </Button>
            <Button onClick={() => handleComplete("alice")} variant="secondary" size="sm" className="ml-2">
              <CheckCircle2 className="mr-2 h-4 w-4" /> Mark complete
            </Button>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}

function toEmbed(url: string): string | null {
  try {
    const u = new URL(url);
    if (u.hostname.includes("youtube.com") || u.hostname === "youtu.be") {
      const id = u.hostname === "youtu.be" ? u.pathname.slice(1) : u.searchParams.get("v");
      return id ? `https://www.youtube.com/embed/${id}` : null;
    }
    if (u.hostname.includes("vimeo.com")) {
      const id = u.pathname.split("/").filter(Boolean).pop();
      return id ? `https://player.vimeo.com/video/${id}` : null;
    }
    return url;
  } catch { return null; }
}
