ALTER TABLE public.notes 
  ADD COLUMN IF NOT EXISTS position_x real DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS position_y real DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS cover_color text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS icon text DEFAULT NULL;