// Shared catalog of prebuilt macros for the ALICE Macro Suite.
// Mirrors the structure of `extension/prebuilt-macros.js` so they can be
// installed from either the web app or the Toolbox extension.

export type PrebuiltStep = Record<string, any> & { action: string };

export interface PrebuiltMacro {
  slug: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  start_url: string;
  target_domain: string | null;
  tags: string[];
  steps: PrebuiltStep[];
}

export const PREBUILT_MACROS: PrebuiltMacro[] = [
  // ── Email ────────────────────────────────────────────
  {
    slug: "gmail-compose",
    name: "Compose new Gmail",
    description: "Open Gmail and start a fresh compose window.",
    category: "Email",
    icon: "✉️",
    start_url: "https://mail.google.com/mail/u/0/#inbox?compose=new",
    target_domain: "mail.google.com",
    tags: ["gmail", "email"],
    steps: [
      { action: "navigate", url: "https://mail.google.com/mail/u/0/#inbox?compose=new" },
      { action: "wait_for", selector: 'div[role="dialog"][aria-label*="essage" i]' },
      { action: "pause", prompt: "Compose window is open — fill it out and send when ready." },
    ],
  },
  {
    slug: "gmail-inbox-zero",
    name: "Gmail — Inbox Zero pass",
    description: "Opens Gmail, then pauses on each unread thread for you to archive / reply.",
    category: "Email",
    icon: "📥",
    start_url: "https://mail.google.com/mail/u/0/#inbox",
    target_domain: "mail.google.com",
    tags: ["gmail", "inbox"],
    steps: [
      { action: "navigate", url: "https://mail.google.com/mail/u/0/#inbox" },
      { action: "wait_for", selector: 'div[role="main"]' },
      { action: "pause", prompt: "Triage your inbox — archive, reply, or snooze. Click Continue when finished." },
    ],
  },
  {
    slug: "gmail-search-unread",
    name: "Gmail — find unread from sender",
    description: "Search Gmail for unread mail from a specific sender.",
    category: "Email",
    icon: "🔍",
    start_url: "https://mail.google.com",
    target_domain: "mail.google.com",
    tags: ["gmail", "search"],
    steps: [
      { action: "ask", prompt: "Sender email or name", var: "sender" },
      { action: "navigate", url: "https://mail.google.com/mail/u/0/#search/from%3A{{var.sender}}+is%3Aunread" },
      { action: "wait_for", selector: 'div[role="main"]' },
    ],
  },
  {
    slug: "outlook-compose",
    name: "Outlook — new email",
    description: "Open Outlook Web and start a new message.",
    category: "Email",
    icon: "📧",
    start_url: "https://outlook.live.com/mail/0/deeplink/compose",
    target_domain: "outlook.live.com",
    tags: ["outlook", "email"],
    steps: [
      { action: "navigate", url: "https://outlook.live.com/mail/0/deeplink/compose" },
      { action: "pause", prompt: "Compose your message and send." },
    ],
  },

  // ── Productivity ─────────────────────────────────────
  {
    slug: "calendar-new-event",
    name: "New Google Calendar event",
    description: "Jumps straight to the Google Calendar event creator.",
    category: "Productivity",
    icon: "📅",
    start_url: "https://calendar.google.com/calendar/u/0/r/eventedit",
    target_domain: "calendar.google.com",
    tags: ["calendar", "event"],
    steps: [
      { action: "navigate", url: "https://calendar.google.com/calendar/u/0/r/eventedit" },
      { action: "wait_for", selector: 'input[aria-label*="title" i], input[placeholder*="title" i]' },
      { action: "pause", prompt: "Fill in your event details, then save." },
    ],
  },
  {
    slug: "calendar-today",
    name: "Calendar — today's agenda",
    description: "Opens Google Calendar's day view for today.",
    category: "Productivity",
    icon: "🗓️",
    start_url: "https://calendar.google.com/calendar/u/0/r/day",
    target_domain: "calendar.google.com",
    tags: ["calendar", "agenda"],
    steps: [
      { action: "navigate", url: "https://calendar.google.com/calendar/u/0/r/day" },
      { action: "wait_for", selector: 'div[role="main"]' },
    ],
  },
  {
    slug: "drive-new-doc",
    name: "New Google Doc",
    description: "Creates a blank Google Doc in your Drive.",
    category: "Productivity",
    icon: "📝",
    start_url: "https://docs.google.com/document/u/0/create",
    target_domain: "docs.google.com",
    tags: ["docs", "google"],
    steps: [
      { action: "navigate", url: "https://docs.google.com/document/u/0/create" },
      { action: "wait_for", selector: "div.kix-appview-editor, body" },
      { action: "pause", prompt: "Your new doc is ready." },
    ],
  },
  {
    slug: "sheets-new",
    name: "New Google Sheet",
    description: "Creates a blank Google Sheet.",
    category: "Productivity",
    icon: "📊",
    start_url: "https://docs.google.com/spreadsheets/u/0/create",
    target_domain: "docs.google.com",
    tags: ["sheets", "google"],
    steps: [
      { action: "navigate", url: "https://docs.google.com/spreadsheets/u/0/create" },
      { action: "wait_for", selector: "body" },
      { action: "pause", prompt: "Your new sheet is ready." },
    ],
  },
  {
    slug: "slides-new",
    name: "New Google Slides deck",
    description: "Creates a blank presentation.",
    category: "Productivity",
    icon: "🎞️",
    start_url: "https://docs.google.com/presentation/u/0/create",
    target_domain: "docs.google.com",
    tags: ["slides", "google"],
    steps: [
      { action: "navigate", url: "https://docs.google.com/presentation/u/0/create" },
      { action: "wait_for", selector: "body" },
      { action: "pause", prompt: "Your new deck is ready." },
    ],
  },
  {
    slug: "notion-quick-note",
    name: "Notion — quick capture",
    description: "Opens Notion and pauses for you to add a note.",
    category: "Productivity",
    icon: "🟫",
    start_url: "https://www.notion.so",
    target_domain: "www.notion.so",
    tags: ["notion", "notes"],
    steps: [
      { action: "navigate", url: "https://www.notion.so" },
      { action: "pause", prompt: "Pick a page and capture your note." },
    ],
  },

  // ── Research ─────────────────────────────────────────
  {
    slug: "google-search",
    name: "Google search a topic",
    description: "Asks you for a topic, then runs a Google search.",
    category: "Research",
    icon: "🔎",
    start_url: "https://www.google.com",
    target_domain: "www.google.com",
    tags: ["search", "research"],
    steps: [
      { action: "ask", prompt: "What should I search for?", var: "topic" },
      { action: "navigate", url: "https://www.google.com/search?q={{var.topic}}" },
      { action: "wait_for", selector: "#search" },
    ],
  },
  {
    slug: "scholar-search",
    name: "Google Scholar search",
    description: "Search academic literature on Google Scholar.",
    category: "Research",
    icon: "🎓",
    start_url: "https://scholar.google.com",
    target_domain: "scholar.google.com",
    tags: ["scholar", "academic"],
    steps: [
      { action: "ask", prompt: "Scholar query", var: "q" },
      { action: "navigate", url: "https://scholar.google.com/scholar?q={{var.q}}" },
      { action: "wait_for", selector: "#gs_res_ccl" },
    ],
  },
  {
    slug: "wikipedia-search",
    name: "Wikipedia lookup",
    description: "Search Wikipedia for a term.",
    category: "Research",
    icon: "📚",
    start_url: "https://en.wikipedia.org",
    target_domain: "en.wikipedia.org",
    tags: ["wikipedia", "reference"],
    steps: [
      { action: "ask", prompt: "Topic to look up", var: "topic" },
      { action: "navigate", url: "https://en.wikipedia.org/w/index.php?search={{var.topic}}" },
      { action: "wait_for", selector: "#content" },
    ],
  },
  {
    slug: "youtube-search",
    name: "YouTube search",
    description: "Search YouTube for whatever you type.",
    category: "Research",
    icon: "📺",
    start_url: "https://www.youtube.com",
    target_domain: "www.youtube.com",
    tags: ["youtube", "video"],
    steps: [
      { action: "ask", prompt: "Search YouTube for…", var: "q" },
      { action: "navigate", url: "https://www.youtube.com/results?search_query={{var.q}}" },
      { action: "wait_for", selector: "ytd-search" },
    ],
  },
  {
    slug: "summarize-current",
    name: "Summarize current page to a card",
    description: "Sends the current page to ALICE and saves the summary as a Zettel card.",
    category: "Research",
    icon: "🧠",
    start_url: "",
    target_domain: null,
    tags: ["alice", "summary"],
    steps: [{ action: "summarize_page" }],
  },
  {
    slug: "save-page-card",
    name: "Save page → Zettel card",
    description: "Captures the page title + URL + selected text into a new card.",
    category: "Research",
    icon: "🗂️",
    start_url: "",
    target_domain: null,
    tags: ["clip", "alice"],
    steps: [
      { action: "extract_text", selector: "body", var: "page" },
      { action: "alice_chat", prompt: "Save this clipping as a Zettel card:\n\n{{var.page}}" },
    ],
  },
  {
    slug: "translate-clipboard",
    name: "Google Translate a phrase",
    description: "Asks for a phrase, then opens Google Translate with it.",
    category: "Research",
    icon: "🌐",
    start_url: "https://translate.google.com",
    target_domain: "translate.google.com",
    tags: ["translate", "language"],
    steps: [
      { action: "ask", prompt: "Phrase to translate", var: "text" },
      { action: "ask", prompt: "Target language code (e.g. es, fr, de, ja)", var: "lang" },
      { action: "navigate", url: "https://translate.google.com/?sl=auto&tl={{var.lang}}&text={{var.text}}&op=translate" },
      { action: "wait_for", selector: "span[lang]" },
    ],
  },

  // ── Developer ────────────────────────────────────────
  {
    slug: "github-new-repo",
    name: "GitHub — new repository",
    description: "Opens the New Repository page and pauses for you to configure it.",
    category: "Developer",
    icon: "🐙",
    start_url: "https://github.com/new",
    target_domain: "github.com",
    tags: ["github", "developer"],
    steps: [
      { action: "navigate", url: "https://github.com/new" },
      { action: "wait_for", selector: 'input[name="repository[name]"], input#repository_name' },
      { action: "pause", prompt: "Fill in repo name, visibility, and options, then create." },
    ],
  },
  {
    slug: "github-notifications",
    name: "GitHub — unread notifications",
    description: "Jump to your unread GitHub notifications.",
    category: "Developer",
    icon: "🔔",
    start_url: "https://github.com/notifications",
    target_domain: "github.com",
    tags: ["github", "notifications"],
    steps: [
      { action: "navigate", url: "https://github.com/notifications?query=is%3Aunread" },
      { action: "wait_for", selector: "main" },
    ],
  },
  {
    slug: "stackoverflow-search",
    name: "Stack Overflow search",
    description: "Search Stack Overflow for an error or question.",
    category: "Developer",
    icon: "💬",
    start_url: "https://stackoverflow.com",
    target_domain: "stackoverflow.com",
    tags: ["stackoverflow", "search"],
    steps: [
      { action: "ask", prompt: "Question or error", var: "q" },
      { action: "navigate", url: "https://stackoverflow.com/search?q={{var.q}}" },
      { action: "wait_for", selector: ".js-search-results" },
    ],
  },
  {
    slug: "mdn-search",
    name: "MDN docs lookup",
    description: "Search MDN web docs.",
    category: "Developer",
    icon: "📘",
    start_url: "https://developer.mozilla.org",
    target_domain: "developer.mozilla.org",
    tags: ["mdn", "docs"],
    steps: [
      { action: "ask", prompt: "API or term", var: "q" },
      { action: "navigate", url: "https://developer.mozilla.org/en-US/search?q={{var.q}}" },
      { action: "wait_for", selector: "main" },
    ],
  },
  {
    slug: "npm-package",
    name: "Look up npm package",
    description: "Opens the npm page for a package you name.",
    category: "Developer",
    icon: "📦",
    start_url: "https://www.npmjs.com",
    target_domain: "www.npmjs.com",
    tags: ["npm", "developer"],
    steps: [
      { action: "ask", prompt: "Package name", var: "pkg" },
      { action: "navigate", url: "https://www.npmjs.com/package/{{var.pkg}}" },
      { action: "wait_for", selector: "main" },
    ],
  },

  // ── Social ───────────────────────────────────────────
  {
    slug: "linkedin-post",
    name: "LinkedIn — start a post",
    description: "Opens the LinkedIn composer.",
    category: "Social",
    icon: "💼",
    start_url: "https://www.linkedin.com/feed/",
    target_domain: "www.linkedin.com",
    tags: ["linkedin", "social"],
    steps: [
      { action: "navigate", url: "https://www.linkedin.com/feed/" },
      { action: "wait_for", selector: 'button[aria-label*="Start a post" i]' },
      { action: "click", selector: 'button[aria-label*="Start a post" i]' },
      { action: "pause", prompt: "Write your post and click Post when ready." },
    ],
  },
  {
    slug: "x-compose",
    name: "X (Twitter) — compose post",
    description: "Opens the X composer dialog.",
    category: "Social",
    icon: "𝕏",
    start_url: "https://x.com/compose/post",
    target_domain: "x.com",
    tags: ["twitter", "x", "social"],
    steps: [
      { action: "navigate", url: "https://x.com/compose/post" },
      { action: "pause", prompt: "Write your post and hit Post." },
    ],
  },
  {
    slug: "reddit-submit",
    name: "Reddit — submit to subreddit",
    description: "Opens the submission form for any subreddit.",
    category: "Social",
    icon: "👽",
    start_url: "https://www.reddit.com",
    target_domain: "www.reddit.com",
    tags: ["reddit", "social"],
    steps: [
      { action: "ask", prompt: "Subreddit name (without r/)", var: "sub" },
      { action: "navigate", url: "https://www.reddit.com/r/{{var.sub}}/submit" },
      { action: "pause", prompt: "Compose and submit your post." },
    ],
  },

  // ── Shopping ─────────────────────────────────────────
  {
    slug: "amazon-orders",
    name: "Amazon — review recent orders",
    description: "Jumps to your Amazon orders page.",
    category: "Shopping",
    icon: "📦",
    start_url: "https://www.amazon.com/gp/your-account/order-history",
    target_domain: "www.amazon.com",
    tags: ["amazon", "shopping"],
    steps: [
      { action: "navigate", url: "https://www.amazon.com/gp/your-account/order-history" },
      { action: "wait_for", selector: "body" },
      { action: "pause", prompt: "Review your recent orders." },
    ],
  },
  {
    slug: "amazon-search",
    name: "Amazon — product search",
    description: "Searches Amazon for a product.",
    category: "Shopping",
    icon: "🛒",
    start_url: "https://www.amazon.com",
    target_domain: "www.amazon.com",
    tags: ["amazon", "search"],
    steps: [
      { action: "ask", prompt: "What are you shopping for?", var: "item" },
      { action: "navigate", url: "https://www.amazon.com/s?k={{var.item}}" },
      { action: "wait_for", selector: '[data-component-type="s-search-result"]' },
    ],
  },
  {
    slug: "ebay-search",
    name: "eBay — search listings",
    description: "Search eBay for an item.",
    category: "Shopping",
    icon: "🏷️",
    start_url: "https://www.ebay.com",
    target_domain: "www.ebay.com",
    tags: ["ebay", "shopping"],
    steps: [
      { action: "ask", prompt: "What to search on eBay?", var: "item" },
      { action: "navigate", url: "https://www.ebay.com/sch/i.html?_nkw={{var.item}}" },
      { action: "wait_for", selector: "#srp-river-results" },
    ],
  },

  // ── Travel ───────────────────────────────────────────
  {
    slug: "flight-search",
    name: "Google Flights — search",
    description: "Opens Google Flights with from/to/date prefilled.",
    category: "Travel",
    icon: "✈️",
    start_url: "https://www.google.com/travel/flights",
    target_domain: "www.google.com",
    tags: ["travel", "flights"],
    steps: [
      { action: "navigate", url: "https://www.google.com/travel/flights" },
      { action: "pause", prompt: "Pick origin, destination, and dates. Click Search." },
    ],
  },
  {
    slug: "maps-directions",
    name: "Google Maps — directions",
    description: "Opens directions between two addresses.",
    category: "Travel",
    icon: "🗺️",
    start_url: "https://www.google.com/maps",
    target_domain: "www.google.com",
    tags: ["maps", "directions"],
    steps: [
      { action: "ask", prompt: "Starting address", var: "from" },
      { action: "ask", prompt: "Destination", var: "to" },
      { action: "navigate", url: "https://www.google.com/maps/dir/{{var.from}}/{{var.to}}" },
      { action: "wait_for", selector: "#scene" },
    ],
  },

  // ── Finance ──────────────────────────────────────────
  {
    slug: "stock-quote",
    name: "Stock quote lookup",
    description: "Opens Google Finance for a ticker.",
    category: "Finance",
    icon: "📈",
    start_url: "https://www.google.com/finance",
    target_domain: "www.google.com",
    tags: ["finance", "stocks"],
    steps: [
      { action: "ask", prompt: "Ticker symbol (e.g. AAPL)", var: "ticker" },
      { action: "navigate", url: "https://www.google.com/finance/quote/{{var.ticker}}:NASDAQ" },
      { action: "wait_for", selector: "main" },
    ],
  },
  {
    slug: "bank-login-template",
    name: "Bank login (template)",
    description: "Generic template to log into a bank using vault credentials. Edit the URL and selectors for your bank.",
    category: "Finance",
    icon: "🏦",
    start_url: "",
    target_domain: null,
    tags: ["bank", "vault", "template"],
    steps: [
      { action: "ask", prompt: "Bank login URL", var: "url" },
      { action: "navigate", url: "{{var.url}}" },
      {
        action: "login_vault",
        user_selector: 'input[type="email"], input[name*="user" i], input[id*="user" i]',
        pass_selector: 'input[type="password"]',
        value: { username: "{{vault.username}}", password: "{{vault.password}}" },
      },
      { action: "pause", prompt: "Solve any 2FA / security questions, then continue." },
    ],
  },

  // ── Auth / Utility ───────────────────────────────────
  {
    slug: "login-vault-generic",
    name: "Log in using vault credentials",
    description: "Auto-fills username/password on the active site from your secure vault. Edit selectors per site.",
    category: "Auth",
    icon: "🔐",
    start_url: "",
    target_domain: null,
    tags: ["login", "vault"],
    steps: [
      {
        action: "login_vault",
        user_selector: 'input[type="email"], input[name*="user" i], input[name*="email" i]',
        pass_selector: 'input[type="password"]',
        value: { username: "{{vault.username}}", password: "{{vault.password}}" },
      },
      { action: "pause", prompt: "Solve any CAPTCHA / 2FA, then continue." },
    ],
  },
  {
    slug: "clear-site-cookies",
    name: "Clear current site & reload",
    description: "Pauses for you to clear cookies for the active site, then reloads.",
    category: "Utility",
    icon: "🧹",
    start_url: "",
    target_domain: null,
    tags: ["utility", "cookies"],
    steps: [
      { action: "pause", prompt: "Open DevTools → Application → Clear site data, then click Continue." },
      { action: "reload" },
    ],
  },
  {
    slug: "copy-page-url",
    name: "Copy page URL & title",
    description: "Copies the current tab's title + URL to your clipboard.",
    category: "Utility",
    icon: "📋",
    start_url: "",
    target_domain: null,
    tags: ["clipboard", "utility"],
    steps: [
      { action: "extract_text", selector: "title", var: "title" },
      { action: "copy_to_clipboard", text: "{{var.title}} — {{page.url}}" },
      { action: "notify", text: "Page link copied to clipboard." },
    ],
  },

  // ── Routines ─────────────────────────────────────────
  {
    slug: "morning-brief",
    name: "Morning brief",
    description: "Opens Gmail inbox, then asks ALICE for a brief on emails, calendar, and tasks.",
    category: "Routines",
    icon: "☀️",
    start_url: "https://mail.google.com/mail/u/0/#inbox",
    target_domain: null,
    tags: ["routine", "morning"],
    steps: [
      { action: "navigate", url: "https://mail.google.com/mail/u/0/#inbox" },
      { action: "wait", ms: 1000 },
      { action: "alice_chat", prompt: "Give me my morning brief: top 3 emails, today's calendar, and any overdue tasks." },
    ],
  },
  {
    slug: "shutdown-routine",
    name: "End-of-day shutdown",
    description: "Walks through inbox triage, tomorrow's calendar, and an ALICE wrap-up reflection.",
    category: "Routines",
    icon: "🌙",
    start_url: "https://mail.google.com/mail/u/0/#inbox",
    target_domain: null,
    tags: ["routine", "evening"],
    steps: [
      { action: "navigate", url: "https://mail.google.com/mail/u/0/#inbox" },
      { action: "pause", prompt: "Triage remaining email." },
      { action: "navigate", url: "https://calendar.google.com/calendar/u/0/r/day" },
      { action: "pause", prompt: "Glance at tomorrow's calendar." },
      { action: "alice_chat", prompt: "Give me a 3-line reflection on today and the top priority for tomorrow." },
    ],
  },
  {
    slug: "weekly-review",
    name: "Weekly review",
    description: "Opens calendar week view and asks ALICE to summarize the week.",
    category: "Routines",
    icon: "📆",
    start_url: "https://calendar.google.com/calendar/u/0/r/week",
    target_domain: null,
    tags: ["routine", "weekly"],
    steps: [
      { action: "navigate", url: "https://calendar.google.com/calendar/u/0/r/week" },
      { action: "wait", ms: 800 },
      { action: "alice_chat", prompt: "Summarize last week's wins, misses, and the top 3 focus areas for next week." },
    ],
  },
];

export const PREBUILT_CATEGORIES = Array.from(
  new Set(PREBUILT_MACROS.map((m) => m.category))
);
